name: kbstudio
on:
  # Define the event that triggers this workflow
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      # Add the environment variable setup step here
      - name: Set up environment variables
        run: echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> $GITHUB_ENV

      # Add other steps of your workflow below (e.g., checkout, build, etc.)
      - name: Checkout repository
        uses: actions/checkout@v2

      # ... other steps of your workflow ...

      - name: Run your script
        run: node main.js
          # Your script commands go here, which use the PEXELS_API_KEY environment variable
